from mysql import connector as m
from list_dict import *
from datetime import date
from autogenerate import autogen_pid, autogen_bid, autogen_rid
from tk6_admform import *
from tk1_pdetails import patient_details

def registeration():
    con = m.connect(host='localhost', user='root', password='mysql', database='silverline_hospital')
    line = con.cursor()
    # for no beds available:
    entryfull = "select * from room_details where Room_Type = 'Private Room' or Room_Type = 'Sharing Room'" \
                "or Room_Type = 'General Ward Bed' and Availability = 0"
    line.execute(entryfull)
    result = list(line.fetchall())
    if result == [None]:
        print('CURRENTLY, THERE IS NO SPACE AVAILABLE IN HOSPITAL. APOLOGIES FOR THE INCONVENIENCE')
        return 0
    p_id = autogen_pid()    #autogenerated IDs
    b_id = autogen_bid()
    #inputs from tkinter admission form:
    try:
        name, aadhar, mob, trtmnt_nm, room_cat, insurance, insnum = adm_form()
    except ValueError:
        print("Kindly Enter Information to admit the patient!")
        return 0
    t_id = id_generation[trtmnt_nm][0]
    r_no = autogen_rid(admission=True,category=room_cat)
    doc_id = id_generation[trtmnt_nm][1]
    doc_nm = doctors[doc_id][0]
    if insurance == 'No':   #insurance check
        ins_num = None
    else:
        ins_num = insnum
    date_adm = date.today()
    #editions to mysql server:
    query = "insert into patients(Patient_Id, Patient_Name, Room_Number, AadharCard_Number, MobileNumber_Guardian, " \
            "Treatment_Id, Insurance_Number, Date_Admission, Doctor_Id, Bill_Number) values('{}','{}','{}','{}','{}'," \
            "'{}','{}','{}','{}','{}')".format(p_id, name, r_no, aadhar, mob, t_id, ins_num, date_adm, doc_id, b_id)
    line.execute(query)
    query1 = "update room_details set Availability = 1, Patient_Id = '{}', Doctor_Id = '{}'" \
             "where Room_Number = '{}'".format(p_id, doc_id, r_no)
    line.execute(query1)
    query2 = "insert into change_transaction(Patient_Id,Room_Number,Date_of_Change, Number_of_Days)" \
             "values('{}','{}','{}',{})".format(p_id, r_no, date_adm, 1)
    line.execute(query2)
    con.commit()
    print('Patient Added Successfully!')
    #display for patient details:
    patient_details(p_id, name, aadhar, mob, t_id, trtmnt_nm, ins_num, date_adm, doc_nm, r_no, b_id)
    line.close()
    con.close()